name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tst-race/raceboat/raceboat-plugin-builder:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          # Disables VCS stamping to prevent exit status 128 in containerized builds
          GOFLAGS: "-buildvcs=false"
        run: |
          # Marks the directory as safe for Git to prevent ownership errors
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./build_artifacts.sh

      - name: Create Build Artifact
        run: "tar cvf ${{ github.event.repository.name }}.tar.gz ./kit"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.repository.name }}.tar.gz"
          path: "${{ github.event.repository.name }}.tar.gz"
          retention-days: 10

